# Generated by Django 5.2 on 2025-04-18 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djit_app', '0002_member_joined_date_member_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
