# Generated by Django 5.2 on 2025-04-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_repouser'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='repository_privacy',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
