# Generated by Django 5.2 on 2025-04-18 18:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_repository_repository_privacy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RepoUser',
            new_name='DjitUser',
        ),
    ]
