# Generated by Django 5.2 on 2025-04-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_repouser_djituser'),
    ]

    operations = [
        migrations.AddField(
            model_name='djituser',
            name='bio',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
