# Generated by Django 5.2 on 2025-04-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_djituser_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='djituser',
            name='isSSHSetup',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='repository',
            name='repository_privacy',
            field=models.BooleanField(default=True),
        ),
    ]
